apiVersion: v1
kind: Service
metadata:
  labels:
    type: canary
    #    app: blue-app
  name: canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: canary
      # app: blue-app
  type: NodePort
status:
  loadBalancer: {}
