apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbkhYVGtIVmlHejBoUVlQNDZZUTdjVnJGCmc5MmZCWmJhYlUzTVFFLy9FWUZtWitjTndTM1VLTFZRRnlkWXY3TzJjUTU0RUhMZTJXV3ZqeC9PN3FuSTdzM3AKVThhbDBlWEFGQllLVFJwTmF3MjV1MXVVdnFDT0lFUHpYajVwNTNhb05WZ3FjU3ErYXpKdm1sMURxNjZtSVZVKwp1VThKK2VrTktXeUZ5c0ZiUGJHL3BBV3hOZ3lTUzRnZ0lCMGZzZ3lPQ09IUEc1Vlh1Y2IrdGROUEU2amtNNjZmCnJtVCtBSm51WGdjYlRBd29CQTdyM2M3aUZsZ2xXNnl2eTdmcGFqd2NKdm5UZTFMMEdadnBWa3ZRalpRSk4zYzYKdlREYStEOWd4ZVo0QkgyWGxEbnFpNXpRVUtEVFBiZ0NBNzdmTm1UKzNiK1Azd2g0R3BBUzB5WkpnWDVkQlFJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIaUp0L0hQUHNEbGFOOWpOK0JHbWs1YVZlMUcyRStRCnoxSm5uRUhlV0ZNaDJkYkd1aUVoell1RzlvUzRCaGFEYksxMUJIWGNDME04bGY5R2NjcjlYTzJLNU15STJlTDgKWEVrY25hbCtJNUl0NURYUVRVV1VnNksycWZaY3ZhL3BaaXFaMk1sS2ttWkVFMDFMQUVMRDdJQ1poa0JCNmYvTwpjRFhmek5pcXFKUmE2OXNsK3cwQ205d1k3ZzVtMEdiU3p1WTFOQkVQeW1kSjBSVUJaUC82SXRSblZYaHBHSzZHCmt0S1hCQnpMbnFWWFI4N2psMDFUZ2ZBVUh0QVZmZmlqb0tqUW9SMGJZT3JUSC9kcUxSbFQ2eFdNTWt6bVJsY1YKUmthK00xSnA3b1o4eDlLTjRkOFJyR0grYlNidGp0NURMWjVKRDhhTlNWZ2JabGtWS2xrb1E2az0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
